export { default as iconGoldStar } from '../assets/svg/iconGoldStar';
export { default as iconComments } from '../assets/svg/iconComments';
export { default as iconComments2 } from '../assets/svg/iconComments2';
export { default as iconPlay } from '../assets/svg/iconPlay';
export { default as iconPause } from '../assets/svg/iconPause';
export { default as iconLove } from '../assets/svg/iconLove';
export { default as iconPrevSong } from '../assets/svg/iconPrevSong' ;
export { default as iconNextSong } from '../assets/svg/iconNextSong';
export { default as iconShuffle } from '../assets/svg/iconShuffle';
export { default as iconSong } from '../assets/svg/iconSong';